### ISSUE TITLE
Error when opening chest (Polymer)

### ISSUE THREAD

**Issue by Khikki** [pcal43/amazing-chest#12]
exactly the same problem, error is similar, I can’t open the chest, I also can’t create it on the vanilla client. He is also invisible.
I believe that further polymer support is needed.
```[10:42:53] [Server thread/ERROR] (class_2600) Failed to handle packet net.minecraft.class_2885@2376da04, suppressing error
 java.lang.NullPointerException: null
        at java.util.Objects.requireNonNull(Objects.java:208) ~[?:?]
        at net.pcal.amazingchest.AcIdentifiers.getSingleScreenHandlerType(AcIdentifiers.java:41) ~[amazingchest-0.0.6+1.18.2.jar:?]
        at net.pcal.amazingchest.AcScreenHandler.createSingle(AcScreenHandler.java:33) ~[amazingchest-0.0.6+1.18.2.jar:?]
        at net.pcal.amazingchest.AmazingChestBlockEntity.method_5465(AmazingChestBlockEntity.java:38) ~[amazingchest-0.0.6+1.18.2.jar:?]
        at net.minecraft.class_2621.createMenu(class_2621.java:161) ~[server-intermediary.jar:?]
        at net.minecraft.class_3222.method_17355(class_3222.java:1031) ~[server-intermediary.jar:?]
        at net.minecraft.class_2281.method_9534(class_2281.java:208) ~[server-intermediary.jar:?]
        at net.minecraft.class_4970$class_4971.method_26174(class_4970.java:939) ~[server-intermediary.jar:?]
        at net.minecraft.class_3225.redirect$zlo000$activateWithOptionalCactus(class_3225.java:1529) ~[server-intermediary.jar:?]
        at net.minecraft.class_3225.method_14262(class_3225.java:336) ~[server-intermediary.jar:?]
        at net.minecraft.class_3244.method_12046(class_3244.java:1081) ~[server-intermediary.jar:?]
        at net.minecraft.class_2885.method_12547(class_2885.java:30) ~[server-intermediary.jar:?]
        at net.minecraft.class_2885.method_11054(class_2885.java:8) ~[server-intermediary.jar:?]
        at net.minecraft.class_2600.method_11072(class_2600.java:22) ~[server-intermediary.jar:?]
        at net.minecraft.class_3738.run(class_3738.java:18) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.redirect$zgb000$redirectExecuteTask(class_1255.java:521) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_16075(class_1255.java:131) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:12288) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:784) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_18857(class_1255.java:140) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:769) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.handler$zja000$modifiedRunLoop(MinecraftServer.java:3905) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:676) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:273) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
```

**Comment by pcal43** [comment]
That looks to me like you didn't correctly enable polymer mode.
```
# Uncomment the 'polymer-enabled' line if you want to run this mod on a server that works with vanilla clients
# or clients that don't have the mod installed.
#
# IMPORTANT: your server must have an appropriate version of polymer installed:
# [https://modrinth.com/mod/polymer/versions](https://www.curseforge.com/linkout?remoteUrl=https%253a%252f%252fmodrinth.com%252fmod%252fpolymer%252fversions)
#
# IMPORTANT: setting polymer-enabled will have the following effects for ALL clients connecting to your server:
# - Sorting Chests will appear as Trapped Chests (not custom graphics)
# - Labels will not be localized (all in English)
# - The 'lock button' will not be added to the UI Screen (no protection against messing up your sorting setup)
#
# polymer-enabled = true
```
